version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_taskmanager
    environment:
      MYSQL_ROOT_PASSWORD: umPassword
      MYSQL_DATABASE: taskmanager
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - taskmanager_network

volumes:
  mysql_data:

networks:
  taskmanager_network: